version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: meqlad
      POSTGRES_PASSWORD: meqlad
      POSTGRES_DB: man_united_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.6.0
    command: webserver
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://meqlad:meqlad@postgres:5432/man_united_dw
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - create-admin
    volumes:
      - ./dags:/opt/airflow/dags
    entrypoint: ["sh", "-c", "airflow db init && exec airflow webserver"]

  airflow-scheduler:
    image: apache/airflow:2.6.0
    command: scheduler
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://meqlad:meqlad@postgres:5432/man_united_dw
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    entrypoint: ["sh", "-c", "airflow db init && exec airflow scheduler"]

  create-admin:
    image: apache/airflow:2.6.0
    environment:
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://meqlad:meqlad@postgres:5432/man_united_dw
    depends_on:
      - postgres
    entrypoint: >
      sh -c "airflow db init &&
             airflow users create \
               --username admin \
               --firstname Admin \
               --lastname User \
               --role Admin \
               --email admin@example.com \
               --password admin &&
             echo 'Admin user created'"

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  jupyter:
    image: jupyter/scipy-notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    depends_on:
      - spark

volumes:
  postgres_data:
