version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: meqlad
      POSTGRES_PASSWORD: meqlad
      POSTGRES_DB: man_united_dw
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Airflow with PySpark and Requests installed
  airflow:
    build:
      context: .  # Refers to the current directory where Dockerfile is located
      dockerfile: Dockerfile  # Specifies the custom Dockerfile for Airflow
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://meqlad:meqlad@postgres:5432/man_united_dw
    depends_on:
      - postgres
      - spark
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
    ports:
      - "8080:8080"

  spark:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=master
    ports:
      - "8081:8081"
    volumes:
      - spark_data:/spark/data

  spark-worker:
    image: bitnami/spark:latest
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark:7077
    depends_on:
      - spark
    volumes:
      - spark_data:/spark/data

  jupyter:
    image: jupyter/pyspark-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/notebooks
    depends_on:
      - spark
      - postgres
    command: start-notebook.sh --NotebookApp.token=''

volumes:
  postgres_data:
  spark_data:
